# -*- coding: utf-8 -*-
"""calculadora.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z6hpnmuOmN1wMH9F_AApY2Kh4T9nBGRz
"""

def soma(a,b):
    return a+b

def subtracao(a,b):
    return a-b

def multiplicacao(a,b):
    return a*b

def divisao(a,b):
    return a/b